"""Generate models/README.md from model.toml files without importing CAD code."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from html import escape
import math
from pathlib import Path
import re
import tomllib
from typing import TypedDict, cast
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]


class PreviewSettings(TypedDict, total=False):
    base_color: str
    relief_color: str
    relief_z: float


@dataclass(frozen=True)
class Model:
    folder: Path
    name: str
    description: str
    status: str
    print_tested: bool
    tags: tuple[str, ...]
    research: tuple[str, ...]
    preview: PreviewSettings


def read_model(folder: Path, root: Path = ROOT) -> Model:
    """Validate the metadata contract and its research links."""
    with (folder / "model.toml").open("rb") as stream:
        data: dict[str, object] = tomllib.load(stream)

    def text(key: str) -> str:
        value = data.get(key)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(f"{folder}: {key} must be a nonempty string")
        return value

    def strings(key: str) -> tuple[str, ...]:
        value = data.get(key)
        if not isinstance(value, list):
            raise ValueError(f"{folder}: {key} must be an array of nonempty strings")
        result: list[str] = []
        for item in cast(list[object], value):
            if not isinstance(item, str) or not item.strip():
                raise ValueError(f"{folder}: {key} must be an array of nonempty strings")
            result.append(item)
        return tuple(result)

    name, description, status = text("name"), text("description"), text("status")
    if data.get("units") != "mm":
        raise ValueError(f"{folder}: units must be 'mm'")
    print_tested = data.get("print_tested")
    if not isinstance(print_tested, bool):
        raise ValueError(f"{folder}: print_tested must be a boolean")
    tags, research = strings("tags"), strings("research")
    if not (folder / "model.py").is_file():
        raise ValueError(f"{folder}: missing model.py")
    for reference in research:
        path = (root / reference).resolve()
        if (Path(reference).is_absolute()
                or not path.is_relative_to((root / "research").resolve())
                or not path.is_file()):
            raise ValueError(f"{folder}: research must link to an existing file under research/: {reference}")
    preview = data.get("preview", {})
    if not isinstance(preview, dict) or set(preview) - {"base_color", "relief_color", "relief_z"}:
        raise ValueError(f"{folder}: preview supports base_color, relief_color, and relief_z")
    for key in ("base_color", "relief_color"):
        if key in preview and (
            not isinstance(preview[key], str)
            or re.fullmatch(r"#[0-9a-fA-F]{6}", preview[key]) is None
        ):
            raise ValueError(f"{folder}: preview.{key} must be a #RRGGBB color")
    if "relief_z" in preview:
        height = preview["relief_z"]
        if isinstance(height, bool) or not isinstance(height, (int, float)) or not math.isfinite(height):
            raise ValueError(f"{folder}: preview.relief_z must be finite millimeters")
    if "relief_color" in preview and "relief_z" not in preview:
        raise ValueError(f"{folder}: preview.relief_color requires relief_z")
    return Model(folder, name, description, status, print_tested, tags, research,
                 cast(PreviewSettings, preview))


def discover(root: Path = ROOT) -> list[Model]:
    base = root / "models"
    for source in sorted(base.rglob("model.py")):
        if not source.with_name("model.toml").is_file():
            raise ValueError(f"{source}: missing model.toml; every model needs metadata")
    return [read_model(path.parent, root) for path in sorted(base.rglob("model.toml"))]


def cell(value: str) -> str:
    return escape(value).replace("|", "&#124;").replace("\n", " ").replace("\r", " ")


def catalog(root: Path = ROOT) -> str:
    lines = [
        "# Model catalog", "",
        "<!-- Generated by scripts/index.py; edit model.toml, not this file. -->", "",
        "Regenerated after successful builds, or with `uv run python scripts/index.py`.",
        "Paths identify models; nested folders group related parts. Status is author-declared, not certification.",
        "Print tested records a confirmed physical print of the current geometry, not fit or safety certification.",
        "", "| Model | Path / project | Description | Status | Print tested | Tags | Research |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for model in discover(root):
        relative = model.folder.relative_to(root / "models").as_posix()
        research = ", ".join(
            f"[{cell(Path(ref).parent.name)}]({quote('../' + ref, safe='/')})"
            for ref in model.research
        ) or "—"
        lines.append(
            f"| [{cell(model.name)}]({quote(relative + '/model.py', safe='/')}) "
            f"| {cell(relative)} | {cell(model.description)} | {cell(model.status)} "
            f"| {'Yes' if model.print_tested else 'No'} "
            f"| {cell(', '.join(model.tags))} | {research} |"
        )
    lines.extend(["", "For `models/<path>/`, build artifacts go to `outputs/<path>/` (ignored by Git).",
                  "`preview.html` is an offline rotatable viewer; `preview.png` contains four fixed views.", ""])
    return "\n".join(lines)


def generate(root: Path = ROOT, check: bool = False) -> Path:
    path = root / "models" / "README.md"
    text = catalog(root)
    if check:
        if not path.is_file() or path.read_text() != text:
            raise ValueError("Model catalog is stale; run uv run python scripts/index.py")
    else:
        path.write_text(text)
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the catalog is stale")
    args = parser.parse_args()
    try:
        print(generate(check=args.check))
    except (ValueError, OSError) as error:
        parser.exit(1, f"Catalog error: {error}\n")


if __name__ == "__main__":
    main()
